# Base URL for patient API
@baseUrl = http://localhost:4000

### Save a new patient
POST {{baseUrl}}/patients
Content-Type: application/json

{
  "name": "Pooja Mohanakrishnan",
  "email": "vbalaji215@gmail.com",
  "address": "13377 Batten Lane",
  "dateOfBirth": "1983-05-21",
  "registeredDate": "2024-12-12"
}

###
