spring:
  application:
    name: patient-service
#  h2:
#    console:
#      path: /h2-console
#  datasource:
#    url: jdbc:postgresql://postgres:5432/patient_service_db
#    driver-class-name: org.postgresql.Driver
#    username: patient_service_admin
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#  sql:
#    init:
#      mode: always
server:
  port: 4000
